version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: nuget
    directory: "/source/backend"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
    groups:
      backend:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: "/source/frontend"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
    groups:
      frontend:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: "/source/e2e"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
    groups:
      e2e:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
