// <auto-generated />
using System;
using EstoqueIgreja.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EstoqueIgreja.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925144539_RemoveDoadorMovimentacaoSocial")]
    partial class RemoveDoadorMovimentacaoSocial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.AtualizacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantidadeAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeNova")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ItemId", "Data");

                    b.ToTable("AtualizacoesEstoque");
                });

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstoqueAtual")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("NomeNormalizado")
                        .IsUnique();

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.ItemSocial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstoqueAtual")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("NomeNormalizado")
                        .IsUnique();

                    b.ToTable("ItensSociais");
                });

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.ModeloCesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CestasProntas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ModelosCesta");
                });

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.ModeloCestaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemSocialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeloCestaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemSocialId");

                    b.HasIndex("ModeloCestaId", "ItemSocialId")
                        .IsUnique();

                    b.ToTable("ModeloCestaItens");
                });

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.MontagemCesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CestasAnteriores")
                        .HasColumnType("integer");

                    b.Property<int>("CestasNovas")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MontagensCesta");
                });

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.MovimentacaoSocial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemSocialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MontagemCestaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("QuantidadeAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeNova")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("MontagemCestaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ItemSocialId", "Data");

                    b.ToTable("MovimentacoesSociais");
                });

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AcessoAcaoSocial")
                        .HasColumnType("boolean");

                    b.Property<bool>("AcessoObreiros")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.AtualizacaoEstoque", b =>
                {
                    b.HasOne("EstoqueIgreja.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstoqueIgreja.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.ModeloCestaItem", b =>
                {
                    b.HasOne("EstoqueIgreja.Domain.Entities.ItemSocial", "ItemSocial")
                        .WithMany()
                        .HasForeignKey("ItemSocialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstoqueIgreja.Domain.Entities.ModeloCesta", null)
                        .WithMany("Itens")
                        .HasForeignKey("ModeloCestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemSocial");
                });

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.MontagemCesta", b =>
                {
                    b.HasOne("EstoqueIgreja.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.MovimentacaoSocial", b =>
                {
                    b.HasOne("EstoqueIgreja.Domain.Entities.ItemSocial", "ItemSocial")
                        .WithMany()
                        .HasForeignKey("ItemSocialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstoqueIgreja.Domain.Entities.MontagemCesta", null)
                        .WithMany()
                        .HasForeignKey("MontagemCestaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EstoqueIgreja.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemSocial");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstoqueIgreja.Domain.Entities.ModeloCesta", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
